name: metal_forte
description: A new Flutter project.

publish_to: "none"

version: 0.0.3+6

environment:
  sdk: '3.6.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #UI
  material_symbols_icons: ^4.2661.1

  #NOTIFICATIONS
  overlay_support: ^2.0.1

  #OUTROS
  intl: ^0.19.0
  rxdart: ^0.28.0
  flutter_native_splash: ^2.2.0+1
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  flutter_keyboard_visibility: ^6.0.0
  path_provider: ^2.1.2
  dio: ^5.4.0
  flutter_masked_text2: ^0.9.1
  location: ^6.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.5
  signature: ^5.5.0
  flutter_image_compress: ^2.3.0

  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher/launcher.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#F67B42"
    theme_color: "#F67B42"

flutter_native_splash:
  android: true
  ios: true
  color: "#F67B42"
  image: assets/launcher/splash.png
  android_12:
    image: assets/launcher/splash.png
    icon_background_color: "#F67B42"

  # f pub run flutter_launcher_icons && dart run flutter_native_splash:create

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/launcher/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Black.ttf
          weight: 900

        - asset: assets/fonts/work_sans/WorkSans-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: assets/fonts/work_sans/WorkSans-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/work_sans/WorkSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
          weight: 700

        - asset: assets/fonts/work_sans/WorkSans-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/work_sans/WorkSans-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/work_sans/WorkSans-Medium.ttf
          weight: 500

        - asset: assets/fonts/work_sans/WorkSans-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
          weight: 400

        - asset: assets/fonts/work_sans/WorkSans-Light.ttf
          weight: 300

        - asset: assets/fonts/work_sans/WorkSans-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/work_sans/WorkSans-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/work_sans/WorkSans-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/work_sans/WorkSans-Thin.ttf
          weight: 100

        - asset: assets/fonts/work_sans/WorkSans-ThinItalic.ttf
          weight: 100
          style: italic
